export const SET_CITY = 'SEARCH/SET_CITY';
export const SET_DATEIN = 'SEARCH/SET_DATEIN';
export const SET_NUMBEROFDAYS = 'SEARCH/SET_NUMBEROFDAYS';

export const REQUEST_HOTELS = 'HOTELS/REQUEST_HOTELS';
export const FETCH_HOTELS = 'HOTELS/FETCH_HOTELS';
export const SHOW_LOADER = 'HOTELS/SHOW_LOADER';
export const HIDE_LOADER = 'HOTELS/HIDE_LOADER';

export const ADD_FAVORITE = 'FAVORITES/ADD_FAVORITE';
export const REMOVE_FAVORITE = 'FAVORITES/REMOVE_FAVORITE';